# Generated by Django 5.0.2 on 2024-02-24 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formsData',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullName', models.CharField(default=None, max_length=200)),
                ('phone', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
