# Generated by Django 5.0.2 on 2024-02-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default=None, max_length=200)),
                ('phone', models.BigIntegerField(default=None)),
            ],
        ),
    ]
