# Generated by Django 5.0.2 on 2024-02-24 08:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testAll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsdata',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
