# Generated by Django 5.0.2 on 2024-02-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testAll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsdata',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
