# Generated by Django 5.0.2 on 2024-02-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testAll', '0002_formsdata_id_alter_formsdata_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsdata',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='formsdata',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
